/**
 * Builds the README's results table from one complete round (see round.ts), and refuses anything less.
 *
 *   bun e2e/table.ts <results-dir>                    print the table
 *   bun e2e/table.ts <results-dir> --write <README>   replace the table between its markers
 */
import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { parseArgs } from "node:util";
import { $ } from "bun";
import { roundAttempts, roundColumns, roundRows } from "./round.ts";
import { taskById } from "./tasks.ts";

export const startMarker = "<!-- results:start (generated by e2e/table.ts; don't edit) -->";
export const endMarker = "<!-- results:end -->";

interface Run {
	kind: "run";
	taskId: string | null;
	promptStyle: string | null;
	setup: string;
	sightread: string;
	codemode?: string; // absent before codemode conditions existed
	skill: string;
	documentation: string;
	model: string;
	reasoning: string | null;
	name: string;
	seconds: number;
	verified: boolean;
	providerError?: string | null;
	extension: { revision: string | null; dirty: string[] } | null;
}

interface Experiment {
	kind: "experiment";
	taskId: string | null;
	promptStyle: string | null;
}

/** Everything wrong with a round, one line each; empty when it is complete. */
export function problems(records: (Run | Experiment)[]): string[] {
	const found: string[] = [];
	const runs = records.filter((record): record is Run => record.kind === "run");
	const experiments = records.filter((record): record is Experiment => record.kind === "experiment");
	for (const row of roundRows) {
		const label = `${row.task} (${row.prompt})`;
		if (!experiments.some((item) => item.taskId === row.task && item.promptStyle === row.prompt))
			found.push(`${label}: not run, or didn't finish`);
		for (const column of roundColumns) {
			const cell = runs.filter(
				(run) =>
					run.taskId === row.task &&
					run.promptStyle === row.prompt &&
					run.setup === column.setup &&
					run.sightread === column.sightread,
			);
			const where = `${label}, ${column.heading.replaceAll("`", "")}`;
			if (cell.length !== roundAttempts) found.push(`${where}: ${cell.length} attempts, not ${roundAttempts}`);
			const ended = cell.filter((run) => run.providerError).length;
			if (ended) found.push(`${where}: ${ended} ended by the model provider, so measured nothing`);
		}
	}
	const expected = new Set(roundRows.map((row) => `${row.task} ${row.prompt}`));
	const extra = new Set(
		runs.flatMap((run) =>
			expected.has(`${run.taskId} ${run.promptStyle}`) ? [] : [`${run.taskId} (${run.promptStyle})`],
		),
	);
	for (const item of extra) found.push(`${item}: not part of a round`);
	if (runs.some((run) => run.codemode !== "on")) found.push("some attempts ran without codemode, which a round needs");
	const shorthand = runs.filter((run) => run.setup === "code");
	if (shorthand.some((run) => run.skill !== "shorthand" || run.documentation !== "shipped"))
		found.push("some shorthand attempts ran without the shipped documentation and skill");
	const same = (label: string, values: unknown[]) => {
		const distinct = new Set(values.map((value) => JSON.stringify(value)));
		if (distinct.size > 1) found.push(`attempts differ in ${label}: ${[...distinct].join(", ")}`);
	};
	same(
		"model",
		runs.map((run) => run.model),
	);
	same(
		"reasoning",
		runs.map((run) => run.reasoning),
	);
	same(
		"code revision",
		shorthand.map((run) => run.extension?.revision ?? null),
	);
	if (shorthand.some((run) => run.extension?.dirty.length))
		found.push("some attempts ran uncommitted code; commit it and run the round again");
	return found;
}

export function renderTable(records: (Run | Experiment)[]): string {
	const runs = records.filter((record): record is Run => record.kind === "run");
	const first = runs.map((run) => run.name).toSorted()[0]!;
	const date = new Date(`${first.slice(0, 10)}T00:00:00Z`).toLocaleDateString("en-GB", {
		day: "numeric",
		month: "long",
		year: "numeric",
		timeZone: "UTC",
	});
	const model = runs[0]!.model.split("/").at(-1);
	const header = ["Task", "Prompt", "Files", ...roundColumns.map((column) => column.heading)];
	const rows = roundRows.map((row) => {
		const cells = roundColumns.map((column) => {
			const cell = runs.filter(
				(run) =>
					run.taskId === row.task &&
					run.promptStyle === row.prompt &&
					run.setup === column.setup &&
					run.sightread === column.sightread,
			);
			const passed = cell.filter((run) => run.verified);
			const mean = passed.length ? passed.reduce((sum, run) => sum + run.seconds, 0) / passed.length : Infinity;
			return {
				mean,
				text: !passed.length
					? "failed"
					: `${Math.round(mean)}s${passed.length < cell.length ? ` (${passed.length} of ${cell.length})` : ""}`,
				all: passed.length === cell.length,
			};
		});
		// Bold the fastest setup whose attempts all passed.
		const best = Math.min(...cells.filter((cell) => cell.all).map((cell) => cell.mean));
		const size = /-(\d+)$/.exec(row.task)?.[1] ?? String(Object.keys(taskById(row.task).solution).length);
		return [
			`\`${row.task.replace(/-\d+$/, "")}\``,
			row.prompt,
			size,
			...cells.map((cell) => (cell.all && cell.mean === best ? `**${cell.text}**` : cell.text)),
		];
	});
	return [
		`Measured on ${date} with \`${model}\` (${runs[0]!.reasoning ?? "default"} reasoning), ${roundAttempts} attempts per setup, and Pi's codemode on in every setup.`,
		"",
		line(header),
		line(header.map((_, index) => (index === 1 || index === 0 ? "---" : "---:"))),
		...rows.map(line),
	].join("\n");
}

const line = (cells: string[]) => `| ${cells.join(" | ")} |`;

export async function readRound(directory: string): Promise<(Run | Experiment)[]> {
	const text = await readFile(path.join(directory, "summary.jsonl"), "utf8");
	return text
		.split("\n")
		.filter(Boolean)
		.map((record) => JSON.parse(record));
}

if (import.meta.main) {
	const { values, positionals } = parseArgs({ allowPositionals: true, options: { write: { type: "string" } } });
	if (positionals.length !== 1) throw new Error("usage: bun e2e/table.ts <results-dir> [--write <README>]");
	const records = await readRound(positionals[0]!);
	const found = problems(records);
	if (found.length) {
		console.error(`Not a complete round, so no table:\n${found.map((item) => `  ${item}`).join("\n")}`);
		process.exit(1);
	}
	const table = renderTable(records);
	if (!values.write) console.log(table);
	else {
		const readme = await readFile(values.write, "utf8");
		const start = readme.indexOf(startMarker);
		const end = readme.indexOf(endMarker);
		if (start < 0 || end < start) throw new Error(`${values.write} has no results markers`);
		await writeFile(values.write, `${readme.slice(0, start + startMarker.length)}\n\n${table}\n\n${readme.slice(end)}`);
		await $`${path.join(import.meta.dir, "../node_modules/.bin/oxfmt")} ${values.write}`.quiet();
		console.log(`Wrote the table to ${values.write}.`);
	}
}
